name: Update issue state

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  update-issue-state:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get issue information
        id: get_issue
        run: |
          issue_number=$(echo ${{ github.event.issue.number }})
          issue_url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}" | jq -r '.url')
          issue_title=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${issue_url}" | jq -r '.title')

          echo "Found issue: ${issue_title} (#${issue_number})"

      - name: Get branches from issue
        uses: actions/http-request@v2
        id: branches
        with:
          url: https://api.github.com/repos/:owner/:repo/issues/:issue_number/branches
          method: GET
          headers: |
            Authorization: token ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch names
        run: |
          branches=$(echo ${{ steps.branches.outputs.data }} | jq -r '.[].name')
          echo "Related branches: $branches"

      - name: Update issue state
        if: branches != 'null'
        run: |
          echo "Updating issue state to 'In Progress'"
          curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d '{"fields":{"Status":"In Progress"}}' "${{ steps.get_issue.outputs.url }}"
